INSERT INTO norms
    (question, answer, recall_percent)

VALUES
('What is the name of the horse-like animal with black and white stripes?', 'zebra', 93 ),
('What is the name of the long sleep some animals go through during the entire winter?', 'hibernation', 89),
('What is the name of the rubber object that is hit back and forth by hocky players?', 'puck', 88),
('What is the name of the remains of plants and animals that are found in stone?', 'fossils', 87),
('What precious gem is red?','ruby', 84),
('What is the name of the severe headace that returns periodcally and often is accompanied by nausea?', 'migraine', 84),
('What is the name of author who wrote "Romeo and Juliet"?', 'Shakespeare', 84),
('What is the name of a dried grape','Raisin', 83),
('What is the name of the comic strip character who eats spinach to increase his strength', 'popeye', 82),
('What animal runs the fastest?', 'cheetah', 81),
('What is the name of the process by which plants make their food?', 'photosynthesis', 80),
("What is the name of Dorthy's dog in 'The Wizard of OZ'?", 'toto', 79),
('What is the name of the molten rock that runs down the side of a volcano during an eruption?', 'lava', 79),
('What was the name of supposedly unsinkable ship that sank on its maiden voyage in 1912', 'titanic', 78),
('Which sport uses the terms "gutter" and "alley"?', 'bowling', 78),
('What is the name of a giant ocean wave caused by an earthquake?', 'tsunami', 78),
("What is the term for hitting a volleyball down hard into the opponenet's court", 'spike', 78),
('What is the last name of the villainous captain in the story "Peter Pan"?', 'hook', 78),
("What was the name of tarzan's girlfriend?", 'jane', 78),
('What is the last name of the brothers who flew the first airplane at kitty hawk?', 'wright', 75),
('What is the name for a medical doctor who specializes in cutting the body?', 'Surgeon', 74),
('What is the lasst nmae of the first person to set foot on the moon?', 'Armstrong', 74),
('What is the capital of france', 'paris', 73),
('What is the name of the crime in which a building or property is purposely set on fire?', 'arson', 72),
('What is the name of the short pleated skirt worn by men in Scotland?', 'Kilt', 71),
('What is the name of an inability to sleep?', 'insomnia', 71),
('What is the name for a medical doctor who specializes in disease of the skin?', 'Dermatologist', 69),
('What is the name of the largest ocean on Earth?', 'Pacific', 68),
('What is the name of the ship that carried the Pilgrims to America in 1620', 'Mayflower', 66),
('What is the name for a cyclone that occurs over land?', 'Tornado', 64),
('Which sport is associated with Wimbledon?','tennis', 61),
('What is the name of the bird that cannot fly and is the largest bird on Earth?', 'Ostrich', 60),
('What is the name of the island-city belived since antiquity to have sunk into the ocean?', 'Atlantis', 59),
('What is the name of the lizard that changes its color to match the surroundings?', 'Chameleon', 58),
('What is the name of the thick layer of fat on a whale?', 'blubber', 57),
('What is the last name of the baseball player who had the most home runs in a single season prior to 1961?', 'Ruth', 56),
('What is the name of a young sheep?', 'Lamb', 56),
('What is the largest planet in the solar system?', 'Jupiter', 55),
('What is the name of the navigation instrument used at sea to plot position relative to the magnetic North Pole?', 'Compass', 52),
('What is the term in golf refering to a score of one under par on a particular hole?', 'Birdie', 52),
('Which game uses a rubber ball and little metal pieces?', 'Jacks', 52),
('What is the name of a dried plum', 'Prune', 51),
('In which sport does a rider on horseback hit a ball with his mallet?', 'Polo'),
('What is the name of the legendary one-eyed giant in greek mythology?', 'Cyclops', 50),
('In what park is "Old Faithful" located?', 'Yellowstone', 49),
('What is the name of the poker hand in which all cards are of the same suit?', 'Flush', 48),
('In which sport is the Stanley Cup awarded', 'Hockey', 48),
('What is the name of the chapel whose ceiling was painted by Michelangelo?', 'Sistine', 47),
('Of which country is Baghdad the captial?', 'Iraq', 46),
('What is the name of the liquid protion of whole blood?', 'Plasma', 46),
('What is the name of the city in Italy that is known for its canals?', 'Venice', 45),
('What is the name of the spear like object that is thrown during a track meet?', 'Javelin', 45),
('What is the last name of the man who rode horseback in 1775 to war that the british were coming?', 'Revere', 44),
('Who was the Egyption queen who joined forces with Mark Antony of Rome?', 'Cleopatra', 44),
('What is the last name of the man who assassinated Abraham Lincoln', 'Booth', 43),
('What is the last name of the man who showed that lightning is electric?', 'Franklin', 43),
('What is the last name of the famous magician and escape artist who died of appendictis?', 'Houdini', 43),
('What is the name of deer meat?', 'Venison', 43),
('What is the name of the large hairy spider that lives near bananas?', 'Tarantula', 42),
('What is the name of the ocean that is located between Africa and Australia?', 'Indian', 42),
('What is the last name of the singer who recorded "Heartbreak Hotel" and "All Shook up"?', 'Presley', 42),
('What is the name of the crime in which a person purposely betrays his country?', 'Treason', 41),
('What is the name of the first artificial satellite put in orbit by Russia in 1957?', 'Sputnik', 41),
('What brand of cigarette was first to have the flip-top box?', 'Marlboro', 39),
('What kind of metal is associated with a 50th wedding anniversary?', 'Gold', 39),
('Which type of snake do Asian snake-charmers use?', 'Cobra', 39),
('What is the name of the desert people who wander isntead of living in one place?', 'Nomads', 35),
('What is the capital of New York', 'Albany', 33),
('What is the name of the organ that produces insulin?', 'Pancreas', 32),
('What is the name of the collar bone?', 'Clavicle', 32),
('What is the name of the extinct reptiles known as "Terrible Lizards"', 'Dinosaurs', 31),
('left off at question 73')